// --- NUEVA PLANTILLA: FLASH CARD (LINKEDIN STYLE) ---
function generateCardHTML(data) {
  // Lógica de colores simple
  const da = parseInt(data.da) || 0;
  let daColor = '#ef4444'; // Rojo
  if (da >= 30) daColor = '#eab308'; // Amarillo
  if (da >= 50) daColor = '#22c55e'; // Verde

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
        
        body {
          margin: 0;
          padding: 0;
          width: 1200px;
          height: 630px;
          background: #0f172a; /* Dark Slate */
          font-family: 'Inter', sans-serif;
          color: white;
          display: flex;
          box-sizing: border-box;
        }

        .container {
          display: flex;
          width: 100%;
          height: 100%;
          padding: 60px;
          gap: 50px;
        }

        /* COLUMNA IZQUIERDA: MÉTRICAS */
        .left-col {
          flex: 0 0 400px;
          display: flex;
          flex-direction: column;
          justify-content: center;
          gap: 30px;
          border-right: 1px solid #334155;
          padding-right: 50px;
        }

        .metric-box {
          background: #1e293b;
          padding: 25px;
          border-radius: 16px;
          border: 1px solid #334155;
          text-align: center;
        }

        .metric-label {
          color: #94a3b8;
          text-transform: uppercase;
          font-size: 14px;
          font-weight: 600;
          letter-spacing: 1px;
          margin-bottom: 10px;
          display: block;
        }

        .metric-value {
          font-size: 48px;
          font-weight: 800;
          display: block;
        }

        .da-circle {
            width: 120px;
            height: 120px;
            border-radius: 50%;
            border: 8px solid ${daColor};
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 48px;
            font-weight: 800;
            margin: 0 auto;
            color: white;
            background: #0f172a;
            box-shadow: 0 0 20px ${daColor}40; /* Glow effect */
        }

        /* COLUMNA DERECHA: ANÁLISIS */
        .right-col {
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
        }

        .company-name {
          font-size: 24px;
          color: #38bdf8; /* Sky Blue */
          font-weight: 600;
          margin-bottom: 10px;
          text-transform: uppercase;
          letter-spacing: 1px;
        }

        .title {
          font-size: 42px;
          font-weight: 800;
          line-height: 1.1;
          margin: 0 0 30px 0;
          background: -webkit-linear-gradient(0deg, #fff, #94a3b8);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .analysis-box {
          background: #1e293b;
          border-radius: 16px;
          padding: 30px;
          border-left: 6px solid #38bdf8;
        }

        .analysis-item {
          margin-bottom: 15px;
          font-size: 18px;
          line-height: 1.5;
          color: #e2e8f0;
        }
        .analysis-item strong { color: #fff; }
        .analysis-item:last-child { margin-bottom: 0; }

        .footer {
            margin-top: auto;
            font-size: 14px;
            color: #64748b;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .dot { width: 8px; height: 8px; background: #22c55e; border-radius: 50%; display: inline-block; }

      </style>
    </head>
    <body>
      <div class="container">
        
        <div class="left-col">
            <div class="metric-box" style="border-color: ${daColor}40;">
                <span class="metric-label">Domain Authority</span>
                <div class="da-circle">${da}</div>
            </div>

            <div class="metric-box">
                <span class="metric-label">Est. Organic Traffic</span>
                <span class="metric-value">${data.traffic}</span>
                <span style="font-size: 12px; color: #64748b;">visits / mo</span>
            </div>

             <div class="metric-box">
                <span class="metric-label">Content Audit</span>
                <span class="metric-value" style="font-size: 24px;">${data.content_quality || "N/A"}</span>
            </div>
        </div>

        <div class="right-col">
            <div class="company-name">${data.company}</div>
            <h1 class="title">Growth Audit Snapshot</h1>
            
            <div class="analysis-box">
                ${data.evaluation} 
            </div>

            <div class="footer">
                <span class="dot"></span> Generated by Ekho Engine
            </div>
        </div>

      </div>
    </body>
    </html>
  `;
}

// --- ACTUALIZAR EL ENDPOINT DE IMAGEN ---
app.post('/generate-image', async (req, res) => {
  let browser = null;
  let page = null;
  try {
    const { data } = req.body;
    if (!data) return res.status(400).json({ error: 'No data provided' });

    // AQUI ESTA EL CAMBIO: Usamos la nueva función visual
    const html = generateCardHTML(data); 

    browser = await puppeteer.launch({
      headless: "new",
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--single-process', '--no-zygote']
    });

    page = await browser.newPage();
    // Forzamos tamaño exacto de tarjeta social
    await page.setViewport({ width: 1200, height: 630, deviceScaleFactor: 2 }); 
    
    await page.setContent(html, { waitUntil: 'networkidle0' });

    const image = await page.screenshot({ type: 'png' });

    await page.close();
    await browser.close();

    res.setHeader('Content-Type', 'image/png');
    res.send(image);

  } catch (error) {
    console.error('Error generando Imagen:', error);
    if (page) await page.close().catch(() => {});
    if (browser) await browser.close().catch(() => {});
    res.status(500).json({ error: 'Failed', details: error.message });
  }
});
